name: Check Version Increment
on:
  push:
    branches:
      - feature/readme-n-flow-n-all-specified-mandatory-check
#  pull_request:
#    branches:
#      - main
#      - feature/*
jobs:
  check-version-increment:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check Version
        uses: ./
        with:
          log-level: "TRACE"
          check-only-for: "README.md"

